# Generated by Django 4.1 on 2022-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.CharField(blank=b'I00\n', max_length=20, primary_key=True, serialize=False, verbose_name='Student Id')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
