# Generated by Django 4.0.5 on 2022-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_grades_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=b'I00\n', max_length=20, verbose_name='Course Id')),
                ('result', models.CharField(max_length=50, verbose_name='Result')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
