# Generated by Django 4.0.5 on 2022-08-04 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('University', '0008_grades_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ID', models.CharField(max_length=50, verbose_name='Course ID')),
                ('course_Name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('course_Description', models.CharField(max_length=50, verbose_name='Course Description')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
