# Generated by Django 4.0.5 on 2022-08-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0009_courseregistrations_remove_courseregistration_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistrations',
            name='date_added',
        ),
    ]
